# Generated by Django 5.2 on 2025-05-03 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0001_initial'),
        ('User', '0005_alter_teacherprofile_class_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='class_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='User.schoolclass'),
            preserve_default=False,
        ),
    ]
