# Generated by Django 5.2 on 2025-05-04 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0002_attendance_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 5, 4, 12, 47, 1, 22511, tzinfo=datetime.timezone.utc)),
        ),
    ]
