# Generated by Django 5.2 on 2025-05-03 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_teacherprofile_class_assiging_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='class_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_classes', to='User.schoolclass'),
        ),
    ]
