# Generated by Django 5.2 on 2025-05-04 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_teacherprofile_class_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='hire_date',
            field=models.DateField(default=datetime.datetime(2025, 5, 4, 12, 47, 1, 18489, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddConstraint(
            model_name='studentprofile',
            constraint=models.UniqueConstraint(fields=('student_class', 'roll_no'), name='unique_roll_per_class'),
        ),
    ]
